name: ci

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'releases/v*'

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          image: alpine:3.9
#      -
#        name: Upload scan results to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v1
#        with:
#          sarif_file: ${{ steps.scan.outputs.sarif }}
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

  tarball:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./test
          platforms: linux/amd64,linux/arm64
          outputs: type=docker,dest=/tmp/image.tar
          tags: name/app:latest
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          tarball: /tmp/image.tar
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
