name: ci

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'releases/v*'

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          image: alpine:3.9
      -
        name: JSON result
        run: cat ${{ steps.scan.outputs.json }}
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

  tarball:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./test
          outputs: type=oci,dest=/tmp/image.tar
          tags: name/app:latest
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          tarball: /tmp/image.tar
      -
        name: JSON result
        run: cat ${{ steps.scan.outputs.json }}
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

  sarif:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./test
          outputs: type=oci,dest=/tmp/image.tar
          tags: name/app:latest
      -
        name: Scan for vulnerabilities
        id: scan
        uses: ./
        with:
          tarball: /tmp/image.tar
          dockerfile: ./test/Dockerfile
      -
        name: SARIF result
        run: cat ${{ steps.scan.outputs.sarif }}
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

  annotations:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Scan for vulnerabilities
        uses: ./
        with:
          image: alpine:3.9
          annotations: true
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

  threshold:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Scan for vulnerabilities
        continue-on-error: true
        uses: ./
        with:
          image: alpine:3.9
          severity_threshold: HIGH
      -
        name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
